### ISSUE TITLE
ghc-mod run directory problem

### ISSUE THREAD

**Issue by cblp** [hoovercj/vscode-ghc-mod#27] opened 2016-08-16 09:46 UTC
I have a Stack project consisting of several Cabal components in different subdirectories. This extension always runs ghc-mod tool in the top directory, and when checking a source file inside a sub-project, ghc-mod can't find modules of this sub-project.

But when I run ghc-mod (by hand) in a sub-project directory or in the directory of the source file, it works as expected.

So, I think the extension must run ghc-mod in the directory of the source file, or detect Cabal-file location some other way.

**Comment by hoovercj** [comment] 2016-08-19 16:22
Out of curiosity, does the Atom ghc-mod extension work for you or does it suffer from a similar issue?

Do you have a public repo that I can test this on?

**Comment by archaeron** [comment] 2016-09-02 19:54
I have the same problem. I don't have a public repo to share :(

`ghc-mod` has a command to detect the root folder of a file `ghc-mod root`

Maybe one could call that once for each file.

**Comment by hoovercj** [comment] 2016-09-02 19:58
Can you minimize it/reproduce it to the basics without non-private dependencies?

The reality is that I don't do much Haskell dev but I'm happy to support this project if you give me exact scenarios to support

**Comment by archaeron** [comment] 2016-09-02 22:54
this could be an issue in ghc-mod.

I can't minimize it, i tried.

The isue seems to be that ghc-mod doesn't pick up certain dependencies.
I'll try to find out why and if it's possible to help it.

**Comment by archaeron** [comment] 2016-09-02 23:19
looks like this is my issue: https://github.com/DanielG/ghc-mod/issues/787

**Comment by hoovercj** [comment] 2016-09-03 06:48
Thanks for investigating. It sounds like there's not much I can do so I will close the issue. Feel free to reopen it if you disagree or if something changes.

**Closed as completed by hoovercj** 2016-09-03 06:48 UTC
