### ISSUE TITLE
Needs support for stack and multiproject stack

### ISSUE THREAD

**Issue by newhoggy** [hoovercj/vscode-ghc-mod#12] opened 2016-03-08 22:47 UTC
Currently, if I have a `stack.yaml` file that points to subprojects, the `vscode-ghc-mod` extension doesn't know about it so dependencies between subprojects are not resolved leading to miss "Can not find module" errors.

**Comment by hoovercj** [comment] 2016-05-14 14:32
I haven't used stack. Can you point me to a repo that I can reproduce this on?

I installed stack, cloned [this repo](https://github.com/commercialhaskell/stack), ran `stack build`, and opened VS Code and things seemed to work without errors. But maybe I didn't explore the right edge cases.

If you can give me a more specific setup I'd be happy to investigate further.

**Comment by ghost** [comment] 2016-06-07 08:55
I ran into the same issue. is was finally resolved by downgrading `resolver: lts-6.2` to `resolver: lts-6.0` in `stack.yaml`.   Although I don't know the reason yet. 

EDIT:  It's nothing about resolver version... The solid way to reproduce this issue is to start VS Code from Windows start menu, and then open any project from it.   

Opening VS Code from Command Prompt by running `code` command all things work well. 

The reason is that `stack` executable is not under PATH on my machine. After added it in to PATH, everything works fine.

**Comment by hoovercj** [comment] 2016-06-07 09:50
I'm glad to hear you found a resolution to your issue. I'm going to close this for now.

**Closed as completed by hoovercj** 2016-06-07 09:50 UTC
