### ISSUE TITLE
[TypeError: Cannot read property 'apply' of null]

### ISSUE THREAD

**Issue by Qinka** [hoovercj/vscode-ghc-mod#19] opened 2016-07-13 15:11 UTC
I get this error, with vscode-ghc-mod 0.2.6 and vscode 1.3.1.

I just open a file in vscode.

**Comment by hoovercj** [comment] 2016-07-13 15:29
Please provide more details.

What were you doing when this happened? Hovering over a symbol to get type information? Trying to go to the symbol definition? What did the code look like? Do you have autosave on?

Also, try setting the log level to "log" (add "haskell.ghcMod.logLevel": "log" to your user or workspace settings in vs code) and open the develop console (ctrl+shift+i or use the command palette) and see if there are relevant logs there when you reproduce the error.

**Comment by Qinka** [comment] 2016-07-13 15:50
When I open a haskell source file in vs code, I will get outputs from 'ghc-mod server' : `[TypeError: Cannot read property 'apply' of null]` .  And I set the log level to "log", but got nothing in the develop console. If I open an empty file (such as A.hs) the error is still there.

**Comment by hoovercj** [comment] 2016-07-13 15:56
Was it working for you before and then did it stop working when you upgraded to VS Code 1.3.1?

**Comment by Qinka** [comment] 2016-07-13 16:11
no, on the vs code 1.1.1, there was the same error.

**Comment by hoovercj** [comment] 2016-07-13 16:17
You have ghc-mod installed and in your path? My version is 5.5.0

And no logs like the ones here? If it isn't triggering any logs, it is happening very early.
![image](https://cloud.githubusercontent.com/assets/2957173/16810532/787d53a2-4924-11e6-9981-ca997854e78c.png)

My code doesn't ever call "apply" so it is happening in some dependency and without logs I can't figure out where that might be.

If you want, you can clone this repo to debug it yourself and help me track down the issue. It's a fairly easy process:

```
git clone https://github.com/hoovercj/vscode-ghc-mod.git
cd vscode-ghc-mod
npm install
code client
code server
```

Then in the client window you press `f5` to launch the extension (the launched window will be titled EXTENSION HOST) and in the server window you press `f5` to attach to the client process. Then in the extension host you can open a haskell file and see if you get the error. If you do, look back in the debug console of the other windows to see if there is good information.

**Comment by Qinka** [comment] 2016-07-14 02:54
My ghc-mod's version is 5.5.0.0 and it's compiled with ghc7.10.3 , but the version of ghc in my Mac is 8.0.1. And I uninstalled ghc-7.10.3. I think that may be why it broke down.

**Comment by hoovercj** [comment] 2016-07-29 17:37
I am closing the issue as it seems you have fixed it and/or it is an environment issue, not an issue with the extension.

**Closed as completed by hoovercj** 2016-07-29 17:37 UTC

**Comment by hoovercj** [comment] 2017-02-06 01:51
Added information: the reported error `TypeError: Cannot read property 'apply' of null` was caused by me passing `null` as a callback when registering the extension as a hover and definition provider.

I was likely passing null because ghc-mod couldn't be started.

#46 no longer passes null and instead handles the ghc-mod check in the callbacks, so this should not pollute the logs and should make finding the real issue for users much easier.
